### PR TITLE
Libtorrent and arch build

### PR DESCRIPTION
**Pull request by TobiasTrabelsi**
made code compatible to new libtorrent version and finished PKGBUILD for arch based linux distributions

### CODE REVIEW

**Comment by ArchangeGabriel** [comment]
Your PKGBUILD is not good. I had an old one a long time ago (which is not perfect either), you can still find it here: https://github.com/felixonmars/aur3-mirror/blob/master/roal/PKGBUILD

Especially, the build function shouldn’t do anything git related. And as soon as you’ve put the git repo in the `source` array, it’s going to be cloned anyway.

Also, be sure to separate properly makedepends from runtime depends, and try building in a clean chroot to be sure you didn’t forget anything.

**Comment by ArchangeGabriel** [comment]
I can propose a fixed PKGBUILD if you want. ;) Also, I’m not sure it’s pertinent to have the PKGBUILD here.

**Comment by ArchangeGabriel** [comment]
(And why don’t you use the ROAL repo under QuantumBytesInc in your PKGBUILD?)

**Comment by TobiasTrabelsi** [comment]
@ArchangeGabriel we are trying to build a centralised build structure at the moment to provide an easy to install solution for the most popular linux distributions.
You are right about the repo source. I used my own repository to not affect the real one. will change that soon, as well as providing a debian folder to build a .deb directly from this repository.
Thank you for your feedback on the build section. i had some cache related issues, which resulted in refetching the repo in the build step. if it it proven to be stable on our jenkins servers, I will exclude it again

**Pull request merged**
